name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.13', '1.12' ]

    name: Tests with Go version ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v2-beta
      with:
        go-version: ${{ matrix.go }}

    - name: Confirm Go version
      run: go version

    - name: Confirm Go env
      run: go env

    - name: Confirm system env
      run: env

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Download dependency go modules
      run: make mod-dl

    - name: Install go tools on module-aware mode
      run: GOBIN=$(pwd)/bin make mod-tool-install

    - name: Add PWD/bin into PATH
      run: echo "::add-path::$(pwd)/bin"

    - name: Run tests and linters
      run: make ci

    - name: Run benchmarks
      run: make bench
