name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
      - 'LICENSE'
      - '**/.gitignore'
      - 'Dockerfile'
      - '.dockerignore'
  pull_request:
    paths-ignore:
      - '**/*.md'
      - 'LICENSE'
      - '**/.gitignore'
      - 'Dockerfile'
      - '.dockerignore'

jobs:
  build:
    name: Build with Go version ${{ matrix.go }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'ubuntu-latest' ]
        go: [ '1.13', '1.12' ]
    env:
      CI_BENCH_RESULT: .test/bench.new

    steps:
    - name: Confirm environment information
      id: confirm-env
      run: |
        uname -a
        id
        env

    - name: Dump env context
      id: dump-env-context
      env:
        ENV_CONTEXT: ${{ toJson(env) }}
      run: echo "$ENV_CONTEXT"

    - name: Set up Go ${{ matrix.go }}
      id: setup-go
      uses: actions/setup-go@v2-beta
      with:
        go-version: ${{ matrix.go }}

    - name: Confirm Go version
      id: confirm-go-version
      run: go version

    - name: Confirm Go env
      id: confirm-go-env
      run: go env

    - name: Check out code into the Go module directory
      id: checkout
      uses: actions/checkout@v2

    - name: DEBUG Dump steps context after checkout
      id: debug-steps-context-checkout
      env:
        STEPS_CONTEXT: ${{ toJson(steps) }}
      run: echo "$STEPS_CONTEXT"

    - name: Cache dependencies and tools
      id: cache
      uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Download dependency go modules
      id: mod-dl
      run: make mod-dl

    - name: Install go tools on module-aware mode
      id: mod-tools-install
      run: GOBIN=${GITHUB_WORKSPACE}/bin make mod-tools-install

    - name: Add GITHUB_WORKSPACE/bin into PATH
      id: add-gobin-path
      run: echo "::add-path::${GITHUB_WORKSPACE}/bin"

    - name: Run tests and linters
      id: ci
      run: make ci

    - name: Send a coverage to Codecov
      id: codecov
      uses: codecov/codecov-action@v1
      with:
        # Note: file does not support environment value, context, and expression
        #file: ${{ .env.GITHUB_WORKSPACE }}/coverage.txt
        #file: ${GITHUB_WORKSPACE}/coverage.txt
        file: ./coverage.txt
        flags: unittests
        name: codecov
        fail_ci_if_error: false

    - name: Run benchmarks
      id: bench
      run: make bench

    - name: Upload a current benchmark result
      id: upload-bench-result
      uses: actions/upload-artifact@v1
      with:
        name: benchmark-result
        path: ${{ env.CI_BENCH_RESULT }}
