name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
      - 'LICENSE'
      - '**/.gitignore'
      - 'Dockerfile'
      - '.dockerignore'
  pull_request:
    paths-ignore:
      - '**/*.md'
      - 'LICENSE'
      - '**/.gitignore'
      - 'Dockerfile'
      - '.dockerignore'

jobs:
  debug:
    name: Debug environment information ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'macos-latest', 'windoes-latest' ]

    steps:
    - name: Confirm environment information ${{ matrix.os }}
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
      run: |
        uname -a
        whoami
        env

    - name: Confirm environment information ${{ matrix.os }}
      if: matrix.os == 'windoes-latest'
      run: |
        whoami
        set

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Dump job context
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
      run: echo "$JOB_CONTEXT"

    - name: Dump steps context
      env:
        STEPS_CONTEXT: ${{ toJson(steps) }}
      run: echo "$STEPS_CONTEXT"

    - name: Dump runner context
      env:
        RUNNER_CONTEXT: ${{ toJson(runner) }}
      run: echo "$RUNNER_CONTEXT"

    - name: Dump strategy context
      env:
        STRATEGY_CONTEXT: ${{ toJson(strategy) }}
      run: echo "$STRATEGY_CONTEXT"

    - name: Dump matrix context
      env:
        MATRIX_CONTEXT: ${{ toJson(matrix) }}
      run: echo "$MATRIX_CONTEXT"

  build:
    name: Build with Go version ${{ matrix.go }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.13', '1.12' ]

    steps:
    - name: Confirm environment information
      run: |
        uname -a
        id
        env

    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v2-beta
      with:
        go-version: ${{ matrix.go }}

    - name: Confirm Go version
      run: go version

    - name: Confirm Go env
      run: go env

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Download dependency go modules
      run: make mod-dl

    - name: Install go tools on module-aware mode
      run: GOBIN=${GITHUB_WORKSPACE}/bin make mod-tools-install

    - name: Cache dependencies and tools
      uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Add GITHUB_WORKSPACE/bin into PATH
      run: echo "::add-path::${GITHUB_WORKSPACE}/bin"

    - name: Run tests and linters
      run: make ci

    - name: Send a coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        # Note: file does not support environment value, context, and expression
        #file: ${{ .env.GITHUB_WORKSPACE }}/coverage.txt
        #file: ${GITHUB_WORKSPACE}/coverage.txt
        file: ./coverage.txt
        flags: unittests
        name: codecov
        fail_ci_if_error: false

    - name: Run benchmarks
      run: make bench

    - name: Upload a current benchmark result
      uses: actions/upload-artifact@v1
      with:
        name: benchmark-result
        path: ./.test/bench.new
