name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ 1.12.x', '1.13.x' ]
    name: CI for pull request with version ${{ matrix.go }}
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v2-beta
      with:
        go-version: ${{ matrix.go }}
      run: go version

    - name: Get dependencies
      run: |
        go mod download

    - name: Build
      run: make ci
