name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.13', '1.12' ]

    name: CI for pull request with version ${{ matrix.go }}
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v2-beta
      with:
        go-version: ${{ matrix.go }}

    - name: Confirm Go version
      run: go version

    - name: Confirm envs
      run: env

    - name: Install golint
      run: |
        go install golang.org/x/lint/golint

    - name: Download dependency go modules
      run: |
        go mod download

    - name: Build
      run: make ci
