name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.13', '1.12' ]

    name: CI for pull request with version ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v2-beta
      with:
        go-version: ${{ matrix.go }}

    - name: Confirm Go version
      run: go version

    - name: Confirm Go env
      run: go env

    #   env:
    #     GO111MODULE: off
    #     GOBIN: ${{ env.HOME }}/bin

    # - name: Add HOME/bin into PATH
    #   run: echo "::add-path::${{ env.HOME }}/bin"

    - name: Confirm system env
      run: env

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Download dependency go modules
      run: make mod-dl

    - name: Install go tools from go module
      run: GOBIN=$(pwd)/bin make mod-tool-install
      # env:
      #   GOBIN: $GITHUB_WORKSPACE/bin

    - name: Add HOME/bin into PATH
      run: echo "::add-path::$(pwd)/bin"

    - name: Run tests and lints
      run: make ci

    - name: Run benchmark
      run: make bench

    - name: Show benchmark result
      run: make show-latest-bench
